export * from './normalize.ts';
export { buildRegistry } from './registry.ts';
export { default as megaGengarDeck } from './decks/mega-gengar.json';
export { default as megaDiancieDeck } from './decks/mega-diancie.json';
export { default as megaLucarioDeck } from './decks/mega-lucario.json';
export { default as megaCharizardXDeck } from './decks/mega-charizard-x.json';
export { default as megaVenusaurDeck } from './decks/mega-venusaur.json';
export { default as megaAbomasnowDeck } from './decks/mega-abomasnow.json';
export { default as megaManectricDeck } from './decks/mega-manectric.json';
export { default as megaKangaskhanDeck } from './decks/mega-kangaskhan.json';
export { default as megaLopunnyDeck } from './decks/mega-lopunny.json';
export { GYM_DECKS, GYM_SET, type GymDeckId } from './gym.ts';
export { isPlayable } from './playable.ts';
export { SETS, setCards, isCollectOnlyEra, type Era } from './sets.ts';
